# Build configuration for Cocot46 Plus with ZMK firmware
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

include:
  - board: nice_nano_v2
    shield: cocot46plus
build:
  settings:
    - CONFIG_INPUT=y
    - CONFIG_ADNS5050=y
    - CONFIG_INPUT_ADNS5050=y