# Build configuration for Cocot46 Plus with ZMK firmware
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

include:
  - board: bmp_boost
    shield: cocot46plus
    snippet: zmk-usb-logging